<a href="https://colab.research.google.com/github/sandeepcoder097/100-days-of-code/blob/master/numpy_tri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

matrix creation


In [0]:
x=np.tri(3,3,k=-1,dtype=np.uint16)
print(x)

[[0 0 0]
 [1 0 0]
 [1 1 0]]
